// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $index from './routes/index.tsx';
import * as $Chat from './islands/Chat.tsx';
import * as $Counter from './islands/Counter.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
	routes: {
		'./routes/_404.tsx': $_404,
		'./routes/_app.tsx': $_app,
		'./routes/_middleware.ts': $_middleware,
		'./routes/index.tsx': $index,
	},
	islands: {
		'./islands/Chat.tsx': $Chat,
		'./islands/Counter.tsx': $Counter,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
