#!/usr/bin/env -S deno run --allow-read --allow-write --allow-env --allow-net --allow-run --unsafely-ignore-certificate-errors=localhost

import { main } from "../src/main.ts";

if (import.meta.main) {
  main();
}
